manifest:
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: thedjnK
      url-base: https://github.com/thedjnK

  projects:
    - name: sdk-nrf
      path: nrf
      remote: nrfconnect
      revision: d3c1da02e942ebc1b105ce7027b468351ec47185
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_nordic
          - loramac-node
          - mbedtls
          - mcuboot
          - nrfxlib
          - oberon-psa-crypto
          - picolibc
          - tinycrypt
          - zcbor
          - zephyr
          - segger
    - name: boards
      remote: thedjnK
      revision: main

  self:
    path: lora-hacks-ng
